name: CI

on:
  pull_request:

jobs:
  code:
    name: Test CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependences
        run: bahmutov/npm-install@v1

      - name: Run test
        run: npm run test
