name: CI

on:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
    - uses: actions/checkout@v1

    - name: set up Node
      uses: actions/setup-node@v1
      with:
        node-version: 14
    
    - name: Install dependences
      run: npm install

    - name: Run test
        run: npm run test:e2e